# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 10 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 10 seconds. The default is every 1 minute.

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['p8s-master.YOUR_DOMAIN:9093','p8s-master.YOUR_DOMAIN:9095']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files: 
  - 'alerting-rules.d/*.rules'
  - 'recording-rules.d/*.rules'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'p8s-slave'
    scrape_interval: 30s
    static_configs:
    - targets: ['localhost:9090']

  # Scrape the telegraf. ALL JOBS' NAMES MUST START WITH job: - except the localhost on p8s.
  - job_name: 'job.telegraf-test1'
    static_configs:
      - targets: ['TARGET_SERVER-01-IP-or-FQDN:h9273','TARGET_SERVER-02-IP-or-FQDN:9273'] #static targets running telegraf

  - job_name: 'dummy'  # This is a default value, it is mandatory.
    file_sd_configs:
      - files:
        - targets.json
