crate_endpoints:
- host: "p8s-db01.YOUR_DOMAIN" # Host to connect to (default: "localhost").
  port: 5432                	 # Port to connect to (default: 5432).
  user: "crate"             	 # Username to use (default: "crate")
  password: ""              	 # Password to use (default: "").
  schema: ""                	 # Schema to use (default: "").
  max_connections: 10       	 # The maximum number of concurrent connections (default: 5).
  enable_tls: false         	 # Whether to connect using TLS (default: false).
  allow_insecure_tls: false 	 # Whether to allow insecure / invalid TLS certificates (default: false).
- host: "p8s-db02.YOUR_DOMAIN" # Host to connect to (default: "localhost").
  port: 5432                	 # Port to connect to (default: 5432).
  user: "crate"             	 # Username to use (default: "crate")
  password: ""              	 # Password to use (default: "").
  schema: ""                	 # Schema to use (default: "").
  max_connections: 10       	 # The maximum number of concurrent connections (default: 5).
  enable_tls: false         	 # Whether to connect using TLS (default: false).
  allow_insecure_tls: false 	 # Whether to allow insecure / invalid TLS certificates (default: false).
